<div id="social-media">
	<ul>
		<li><a href="https://plus.google.com/share?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>" onclick="javascript:void window.open('https://plus.google.com/share?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>','1373305744027','width=500,height=550,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;" alt="Share on Google+!"><img src="<?php bloginfo('template_url'); ?>/images/smicons/googleplus.png" alt="Share on Google+!"></a></li>
		<li><a href="http://www.facebook.com/sharer/sharer.php?u=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>" onclick="javascript:void window.open('http://www.facebook.com/sharer/sharer.php?u=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>','1373305744027','width=500,height=550,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;" alt="Share on Facebook!"><img src="<?php bloginfo('template_url'); ?>/images/smicons/facebook.png" alt="Share on Facebook!"></a></li>
		<li><a href="https://twitter.com/intent/tweet?text=<?php echo esc_attr(get_the_title()); ?>&url=< ?php echo esc_url(get_permalink()); ?>" onclick="javascript:void window.open('https://twitter.com/intent/tweet?text=<?php echo esc_attr(get_the_title()); ?>&url=< ?php echo esc_url(get_permalink()); ?>','1373305744027','width=500,height=550,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;" alt="Share on Twitter!"><img src="<?php bloginfo('template_url'); ?>/images/smicons/twitter.png" alt="Share on Twitter!"></a></li>
		<li><a href="http://www.linkedin.com/shareArticle?mini=true&url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?>&summary=< ?php echo esc_attr(get_the_title()); ?>&source={< ?php echo esc_url(home_url()); ?>" onclick="javascript:void window.open('http://www.linkedin.com/shareArticle?mini=true&url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?>&summary=< ?php echo esc_attr(get_the_title()); ?>&source={< ?php echo esc_url(home_url()); ?>','1373305744027','width=500,height=550,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;" alt="Share on LinkedIn!"><img src="<?php bloginfo('template_url'); ?>/images/smicons/linkedin.png" alt="Share on LinkedIn!"></a></li>
		<li><a href="http://www.stumbleupon.com/submit?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?" onclick="javascript:void window.open('http://www.stumbleupon.com/submit?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?','1373305744027','width=500,height=550,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;" alt="Share on StumbleUpon!"><img src="<?php bloginfo('template_url'); ?>/images/smicons/stumbleupon.png" alt="Share on StumbleUpon!"></a></li>
		<li><a href="http://del.icio.us/post?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?>" onclick="javascript:void window.open('http://del.icio.us/post?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?>','1373305744027','width=500,height=550,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;" alt="Share on Delicious!"><img src="<?php bloginfo('template_url'); ?>/images/smicons/delicious.png" alt="Share on Delicious!"></a></li>
		<li><a href="http://digg.com/submit?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?>" onclick="javascript:void window.open('http://digg.com/submit?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?>','1373305744027','width=500,height=550,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;" alt="Share on Digg!"><img src="<?php bloginfo('template_url'); ?>/images/smicons/digg.png" alt="Share on Digg!"></a></li>
		<li><a href="http://reddit.com/submit?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?>" onclick="javascript:void window.open('http://reddit.com/submit?url=<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>&title=< ?php echo esc_attr(get_the_title()); ?>','1373305744027','width=500,height=550,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;" alt="Share on Reddit!"><img src="<?php bloginfo('template_url'); ?>/images/smicons/reddit.png" alt="Share on Reddit!"></a></li>
	</ul>
</div>